package com.cxxcxx.zinecraft.api.nation;

public enum NationRelationTag {TRADE, INVESTMENT, RELIGIOUS_TIES, MEDIATION, HISTORIC_WAR, ACTIVE_CONFLICT, PROXY_CONFLICT, OCCUPATION, BORDER_TENSION, DIPLOMATIC_EXCLUSION, TECHNOLOGY_TRANSFER}
