modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/z8z6/ZineCraft"
logoFile = "assets/zinecraft/icon.png"
authors = "z8z6z8z6, Ye_xingchen"
description = '''
Zinecraft mod.
'''

[[mixins]]
config = "zinecraft.client.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "terrablender"
type = "required"
versionRange = "[4.1.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ponder"
type = "required"
versionRange = "[1.0.82,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "create"
type = "required"
versionRange = "[6.0.10,6.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ftbquests"
type = "required"
versionRange = "[2101.1.20,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "required"
versionRange = "[9.5.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "l2library"
type = "required"
versionRange = "[3.0.8,3.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "tooltipoverhaul"
type = "required"
versionRange = "[${tooltip_overhaul_version},)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "tacz"
type = "required"
versionRange = "[${tacz_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "yes_steve_model"
type = "required"
versionRange = "[${ysm_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "journeymap"
type = "required"
versionRange = "${journeymap_version_range}"
ordering = "AFTER"
side = "CLIENT"
